name: Build-LaTeX
on: [push]
jobs:
  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile
        uses: patricklam/make-latex-action@v0.4.0
        with:
          working_directory: lectures
          pushback: true
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: pdfs
          path: |
            lectures/L*.pdf
            lectures/notebook.pdf
